Add git actions
FelipeSBarros/crossfire pull request #16
Opened 2023-09-10 02:40 UTC by FelipeSBarros

@cuducos não sabia bem por onde seguir, decidi tentar configurar o github actions para validar os teste, estilo de código e lint.

Levei um tempo (dois commits) para entender que devia (e como) informar o path ao `pyproject.toml`, tanto para a instalação das dependencias usando `poetry` assim como para a execução o test pelo `poetry`.

Acho que esse branch **não** está pronto, pois está retornando o seguinte erro:
```
poetry run -C ./Python/crossfire/python pytest
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.10.2, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/felipe/repos/crossfire
plugins: black-ng-0.4.1, ruff-0.1.1, env-1.0.1
collected 0 items / 1 error                                                                                                                                                              

========================================================================================= ERRORS =========================================================================================
_____________________________________________________________________________ ERROR collecting test session ______________________________________________________________________________
Python/crossfire/crossfire/client.py:33: in __init__
    self.email = config("FOGOCRUZADO_EMAIL")
../../.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/decouple.py:248: in __call__
    return self.config(*args, **kwargs)
../../.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/decouple.py:107: in __call__
    return self.get(*args, **kwargs)
../../.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/decouple.py:92: in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
E   decouple.UndefinedValueError: FOGOCRUZADO_EMAIL not found. Declare it as envvar or define a default value.

During handling of the above exception, another exception occurred:
../../.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py:641: in _importconftest
    mod = import_path(conftestpath, mode=importmode, root=rootpath)
../../.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
../../.pyenv/versions/3.10.2/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
../../.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
Python/crossfire/tests/conftest.py:5: in <module>
    from crossfire.client import Client, Token
Python/crossfire/crossfire/__init__.py:3: in <module>
    from crossfire.load_data import get_fogocruzado  # noqa
Python/crossfire/crossfire/load_data.py:4: in <module>
    from crossfire.fogocruzado_utils import extract_data_api
Python/crossfire/crossfire/fogocruzado_utils.py:8: in <module>
    client = Client()
Python/crossfire/crossfire/client.py:35: in __init__
    raise CredentialsNotFoundError("FOGOCRUZADO_EMAIL")
E   crossfire.client.CredentialsNotFoundError: There's no enviornment variable `FOGOCRUZADO_EMAIL` condigured.
================================================================================ short test summary info =================================================================================
ERROR  - crossfire.client.CredentialsNotFoundError: There's no enviornment variable `FOGOCRUZADO_EMAIL` condigured.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================================== 1 error in 0.66s ====================================================================================

```

Imagino que você não tenha esse erro pois, assim como eu, temos um `.env` com "FOGOCRUZADO_EMAIL" e "FOGOCRUZADO_PASSWORD" definidos. Logo, o `config` decouple não retorna erro.
Repare que já havia comentado isso antes mas acreditei que, ao estarmos tratando a exceção [`UndiefinedValueError`](https://github.com/FelipeSBarros/crossfire/blob/master/Python/crossfire/crossfire/client.py#L34), não teriamos esse problema.

Fico sem saber como solucionar isso.

2023-09-10 12:20 UTC, FelipeSBarros commented
Devo mencionar que esse PR depende do [PR 17](https://github.com/FelipeSBarros/crossfire/compare/master...FelipeSBarros:crossfire:pytest_env?expand=1)?

2023-09-10 15:20 UTC, cuducos commented
> Imagino que você não tenha esse erro pois, assim como eu, temos um `.env` com "FOGOCRUZADO_EMAIL" e "FOGOCRUZADO_PASSWORD" definidos

Pq? Nossos testes, até onde lembro, não dependem de um `.env` nem dessas variáveis de ambiente.

> `poetry run -C ./Python/crossfire/python pytest`

Provavelmente isso faz o ponto de entrada dos testes ser a raíz do repositório, e não `Python/crossfire`. Temos que fazer como fazemos localmente. Entrar no diretório do projeto e depois `cd Python/crossfire`, eu acho.

No GtHub não use _PR 17_. Coloque um `#` e o número da _issue_ ou _PR_. Isso evita que você coloque um link quebrado (no teu caso, _PR 17_ é um link para `https://github.com/FelipeSBarros/crossfire/compare/master...FelipeSBarros:crossfire:pytest_env?expand=1` e não para o #17).

2023-09-10 19:05 UTC, cuducos requested changes

2023-09-10 19:05 UTC, cuducos commented on .github/workflows/github-actions.yml
> +   FOGOCRUZADO_PASSWORD: 'pass'
Como disse no #17, não acho que precisamos disso.

```suggestion
```

2023-09-10 19:23 UTC, cuducos commented on .github/workflows/github-actions.yml
> +   FOGOCRUZADO_PASSWORD: 'pass'
Movi meu `.env` (renomei para `.env.bkp`) e rodei os testes. Passou.

Então insisto: a gente não precisa de variáveis de ambiente para rodar os testes. Provavelmente, como no GitHubActions os testes estão [utilizando um ponto de entrada diferente](https://github.com/FelipeSBarros/crossfire/pull/16#issuecomment-1712841424), isso influencia no funcionamento do mock. 

Posso estar errado. Mas se localmente não preciso de variáveis de ambiente para rodar os testes, injetar variáveis de ambiente no GitHub Actions “só para fazer passar” me leva a crer que estamos perdidos:

* estamos resolvendo um problema sem entender o problema
* estamos testando uma coisa localmente (já q localmente posso me livrar do `.env` e os testes passam)
* e outra coisa na CI (pois temos que definir variáveis de ambiente nela)

Precisamos primeiro entender o porquê os testes passam localmente (sem `.env`) e não passam na CI. Aí sim teremos um problema para achar uma solução : )

2023-09-10 19:26 UTC, cuducos commented on .github/workflows/github-actions.yml
> +        run: poetry run pytest
Pelo jeito precisamos do `cd Python/crossfire` no comando dos testes tb : )

```suggestion
        run: |
          cd Python/crossfire
          poetry run pytest
```

2023-09-10 19:35 UTC, FelipeSBarros commented on .github/workflows/github-actions.yml
> +   FOGOCRUZADO_PASSWORD: 'pass'
Vou respondendo fora de rdem, ok?

> estamos resolvendo um problema sem entender o problema

Ok. Peço desculpas...

> Movi meu .env (renomei para .env.bkp) e rodei os testes. Passou.

Fiz o mesmo aqui. Alías, fiz vários testes, como simplesmente mudar o nome de variável no `.env` e isso já era suficiente para ter o seguinte resultado:
```
(crossfire-py3.10) felipe@felipe-Inspiron-7560:~/repos/crossfire/Python/crossfire$ poetry run pytest
ImportError while loading conftest '/home/felipe/repos/crossfire/Python/crossfire/tests/conftest.py'.
tests/conftest.py:5: in <module>
    from crossfire.client import Client, Token
crossfire/__init__.py:3: in <module>
    from crossfire.load_data import get_fogocruzado  # noqa
crossfire/load_data.py:4: in <module>
    from crossfire.fogocruzado_utils import extract_data_api
crossfire/fogocruzado_utils.py:8: in <module>
    client = Client()
crossfire/client.py:35: in __init__
    raise CredentialsNotFoundError("FOGOCRUZADO_EMAIL")
E   crossfire.client.CredentialsNotFoundError: There's no enviornment variable `FOGOCRUZADO_EMAIL` condigured.
```

Agora volto ao seu ponto inicial, sobre esse erro ser relacionado ao teste ou não. Eu acho que não, não tem a ver com o teste, ainda que ele seja levantado ao rodarmos o teste.
Vamos a outra prova que eu fiz.
Simplesmente, ainda sem um `.env`, simplesmente rodei um import:
```
from crossfire.client import Client
raceback (most recent call last):
  File "/home/felipe/repos/crossfire/Python/crossfire/crossfire/client.py", line 33, in __init__
    self.email = config("FOGOCRUZADO_EMAIL")
  File "/home/felipe/.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/decouple.py", line 248, in __call__
    return self.config(*args, **kwargs)
  File "/home/felipe/.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
  File "/home/felipe/.cache/pypoetry/virtualenvs/crossfire-WqfJa-6U-py3.10/lib/python3.10/site-packages/decouple.py", line 92, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: FOGOCRUZADO_EMAIL not found. Declare it as envvar or define a default value.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/pycharm-community-2022.3.2/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/opt/pycharm-community-2022.3.2/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/felipe/repos/crossfire/Python/crossfire/crossfire/__init__.py", line 3, in <module>
    from crossfire.load_data import get_fogocruzado  # noqa
  File "/opt/pycharm-community-2022.3.2/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/felipe/repos/crossfire/Python/crossfire/crossfire/load_data.py", line 4, in <module>
    from crossfire.fogocruzado_utils import extract_data_api
  File "/opt/pycharm-community-2022.3.2/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/felipe/repos/crossfire/Python/crossfire/crossfire/fogocruzado_utils.py", line 8, in <module>
    client = Client()
  File "/home/felipe/repos/crossfire/Python/crossfire/crossfire/client.py", line 35, in __init__
    raise CredentialsNotFoundError("FOGOCRUZADO_EMAIL")
crossfire.client.CredentialsNotFoundError: There's no enviornment variable `FOGOCRUZADO_EMAIL` condigured.
```
Veja que a linha 33 do crossfire.client é justamente no uso do `config`.

Ao retornar o `.env` como tal (sem o `.bkp`) o import é executado sem problemas.
Será que é algo da minha configuração?

2023-09-10 19:36 UTC, FelipeSBarros commented on .github/workflows/github-actions.yml
> +        run: poetry run pytest
Volto a isso quando tivermos entendido o erro....

2023-09-11 14:52 UTC, cuducos commented
Pronto… era só ajustar os mocks para o novo `load_client` e [agora os testes passam](https://github.com/cuducos/crossfire/actions/runs/6148043360/job/16680870893) 🎉 

Resumo do que eu fiz:

1. Adicionei o `cd Python/crossfire` na etapa do `pytest` na CI 5b360ce8ada7f7465deb3bb8e5fbeb74b5112b5e
2. Evitei clamar `client = Client()` ao importar o módulo `load_data` b3f020245b38e86376af5fd0aff43c70c07d6122
3. Ajustei os mocks para o novo cenário do `load_client` fa543580e06480028410330f25a8caf0e65b5cab

Veja se faz sentido, e vamos conversando. Pode estudar esse meu _textão_ e esses commits e tirar dúvidas. Acho que seria legal vc criar a sua própria solução para essa questão (mesmo q seja reimplementando a minha). Não é algo trivial, então é uma experiência legal : ) O que acha?

2023-09-11 23:55 UTC, FelipeSBarros commented
@cuducos acabei de ler com calma. Nossa, que volta vc teve que dar para entender o problema...
Vi que os commits que vc menciona não estão numa branch.
Eu acho que tem muita coisa para eu aprender. Mas não sei se daria conta de tudo.
O que farei é implementar o que você mencionou e ir estudando alguns pontos. Mas sem muita espectativa... rs
Vou commitando por aqui. abs

2023-09-12 00:41 UTC, FelipeSBarros commented
Agora foi, ufa!
Confesso que menospresei, achei que adicionar essas automatizações seria algo fácil... foi bom pois vimos um problema que não estavamos considerando... O mais doido foi pensar que o erro deflagrado era o mesmo que eu já tinha comentado antes (mas por falta de entendimento do processo a ser desenvolvido). Acho que por isso fiquei como maluco tentando resolver isso...
Proximos passos?
Pensei em criar o teste para a possibilidade de podemos sobreescrever as variáveis de ambiente ao acionar o `Client()`, e depois desenvolver a solução. O que acha?

2023-09-12 02:22 UTC, cuducos approved these changes
Esse foi divertido de debugar e desenvolver junto 🎉

2023-09-12 11:56 UTC, FelipeSBarros commented
@cuducos , antes de fazer o merge, vejo [essa mensagem sua](https://github.com/FelipeSBarros/crossfire/pull/16#discussion_r1320850714) . Ela aparece logo após o seu último comentário
> Esse foi divertido de debugar e desenvolver junto 🎉

E me aparece como "outdated"... Como isso foi corrigido e a CI corre sem erro, entendo que podemos ignorar. Confirma?

![image](https://github.com/FelipeSBarros/crossfire/assets/7208674/c2a1fe9c-2747-4e98-8dbe-8df63675de98)

Se quiser, pode mandar ver no merge, pois hj estarei o dia todo sem poder tocar no código.
Se quiser, me mande umas ideias de como seguir... assim na quarta sigo trabalhando.
Abraço

2023-09-12 12:34 UTC, cuducos commented
> Confirma?

Exato.

> Proximos passos?
> Pensei em criar o teste para a possibilidade de podemos sobreescrever as variáveis de ambiente ao acionar o Client(), e depois desenvolver a solução. O que acha?

Pode ser, uma boa! Outras opções, compartilhando só por compartilhar:

- remover a parte de _cities_ (que, pelo o q entendi, não vai existir mais)
- escrever o método `occurrences` na classe `Client`

2023-09-14 00:55 UTC, merged