adiciona client.cities(), com parametros nomeados, praticamente sem teste
FelipeSBarros/crossfire pull request #29
Opened 2023-09-15 20:44 UTC by FelipeSBarros

Adiciona o endpoint `cities`:
```python
>>>from crossfire.client import Client
>>>client = Client()
>>>cities = client.cities()
>>>cities
                                      id  ...                                              state
0   88959ad9-b2f5-4a33-a8ec-ceff5a572ca5  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
1   9d7b569c-ec84-4908-96ab-3706ec3bfc57  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
2   2cded3bc-5dfa-425b-a274-5c1a4b8838d5  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
3   b920f9ed-fa79-4fc0-bc53-ceb14598fa45  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
4   74000596-0e8d-4762-af55-6fba1db74ceb  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
5   e6aa9117-3816-4f42-a7da-1b4b8eef6cdd  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
6   dbd21829-f83c-4479-86c8-3f2953021740  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
7   d4231ca8-3c08-42e2-b877-ad00cc49cecf  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
8   bd078555-2b04-4e46-a637-e87d70551a04  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
9   5a86d707-02ec-4e09-b497-b000b22f156b  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
10  2a69c719-bffc-4839-b832-1ac02b9e873f  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
11  07335d05-e371-42fd-a8f0-42853ccf1a0f  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
12  7ab2a9b5-7727-4460-8007-eb58b78cc7c9  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
13  6752c981-6a86-4e34-a484-f8b1e2228393  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
14  17d2880a-2295-4a24-a480-96d9fa0d40d4  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
15  712f930a-db93-4363-a3c9-9eccc4f12a5f  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
16  d1bf56cc-6d85-4e6a-a5f5-0ab3f4074be3  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
17  ab6bc6ed-952f-48f9-ad84-cbfd3dde53ba  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
18  82f35929-e84c-4842-8181-1dc45a22785f  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
19  7ee9135d-6f6a-4f95-91bb-c3a5021d409a  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
20  c46741dc-bdd2-43d0-92fc-f4d95ed61bf1  ...  {'id': 'b112ffbe-17b3-4ad0-8f2a-2038745d1d14',...
21  d79d2347-bd0d-40aa-8dcc-04134cffd988  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
22  e37f7ad7-cd64-4279-946a-8d689b9b934b  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
23  d2bd4829-6e04-4911-a748-64711b017f4a  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
24  2d630711-3d4a-4281-abdf-e688ee742dd8  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
25  cf1dcecf-ba29-4ee2-98a4-201ea6338edd  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
26  529bc1b3-61b4-4bc6-b05c-975ba575ad2b  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
27  238d5380-f5cd-4c84-91a0-a143e38f4492  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
28  4d4d7540-b41b-4e7c-96d6-c48f7619489a  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
29  440bef67-1518-4a24-ae56-5b95a167244e  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
30  5bd3bfe5-4989-4bc3-a646-fe77a876fce0  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
31  fb3e9596-6b31-46be-b70f-b51b91b9cde8  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
32  5a91501f-3155-4b72-84f2-c42ad1bed3d9  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
33  19b4344f-e157-4618-af94-a9c3d502c035  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
34  fb1c4e7d-1f61-4a86-b514-d93d533df7a3  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
35  3d11bf52-0213-4d6f-a607-77f172cbe3b6  ...  {'id': '813ca36b-91e3-4a18-b408-60b27a1942ef',...
36  4ff3171f-bb7d-4e3a-82e3-aa88bfb68f94  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
37  75cdfe4e-9a54-44f1-99f4-567c7066858b  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
38  4f0f1119-3954-4e8e-a86b-23764e60a63e  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
39  6bbbbb9b-4665-45cb-9ced-013f701a61a3  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
40  1bae1322-1f1d-45f5-8009-7013d26a9a32  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
41  3989630d-1a73-4cf1-aad3-acdc36255b75  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
42  837dee58-bdea-42de-9506-43ba2e0046cf  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
43  7925b7a4-1b7f-4271-a339-2d618e8bcf4f  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
44  8f3a026f-2fc4-419c-9918-f0684a2abbec  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
45  e7e3be75-0adf-4738-85b0-38699bc51623  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
46  241e1eba-0ce2-4d15-89e2-9c579dac265c  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
47  ab216be5-e2ba-45dd-ab9e-bb3cb2295023  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
48  be76d22d-d4c5-468a-96ff-b7a10eefd710  ...  {'id': 'd3a9b545-7056-4dc6-9b68-ce320c9edffc',...
[49 rows x 3 columns]

```
Segue o mesmo padrão de passar o parâmetro `format`, ou outros parâmetros nomeados, para acessar dados de uma cidade em específico (usando `city_id` ou `city_name` ou todas as cidades de um dado estado (usando `state_id`)
```python
>>>citites = client.cities(format='df')
>>>city = client.cities(format='df', city_id='88959ad9-b2f5-4a33-a8ec-ceff5a572ca5')
>>>city = client.cities(format='df', city_name='BELFORD ROXO')
>>>city = client.cities(format='df', state_id='b112ffbe-17b3-4ad0-8f2a-2038745d1d14')
```

Adiciona apenas testes básicos confirmando se método foi chamado uma vez...

2023-09-15 21:12 UTC, cuducos requested changes
Tá ficando bem bom 🎉

2023-09-15 21:12 UTC, cuducos commented on Python/crossfire/crossfire/client.py
> +        return self.get(city_url, format=format)
Não é seguro apenas juntar _string_ para formar parâmetros de URL com valores que vem de quem usa a API. O ideal é usar [uma ferramenta própria para isso](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode).

```suggestion
        params = {"cityId": uuid, "cityName": name, "stateId": state_uuid}
        cleaned = urlencode({key: value for key, value in params.items() if value})
        return self.get(f"{URL}/cities?{cleaned}", format=format)
```

No mais, fico com a impressão que tua função teria um bug com mais de um parâmetro de filtro (URL inválida como `/cities/?name=FourtyTwo?uuid=42` ao invés de `/cities/?name=FourtyTwo&uuid=42`).

2023-09-15 21:12 UTC, cuducos commented on Python/crossfire/tests/test_client.py
> +                    "state.name": "Rio de Janeiro",
Testei manualmente e o que a API retorna acho que é:

```suggestion
                    "state": {
                        "id": "42",
                        "name": "Rio de Janeiro",
                     },
```

2023-09-15 21:12 UTC, cuducos commented on Python/crossfire/tests/test_client.py
> +        assert cities[0]["name"] == "Rio de Janeiro"
Seria legal diferenciar na resposta do mock o nome da cidade e da UF, assim temos certeza que estamos pegando o valor correto aqui : )

2023-09-16 02:17 UTC, cuducos commented on Python/crossfire/tests/test_client.py
> +            "",
Não entendi o porquê desse argumento. O resultado do `urlencode` é parte da URL, não um argumento a mais…

2023-09-18 00:52 UTC, FelipeSBarros commented
@cuducos só agora percebi que vc sugeriu uma forma de acessar o `gities`. Assumi a sua proposta, no [ultimo commit](https://github.com/FelipeSBarros/crossfire/pull/29/commits/dfbbed9dc778f4510b761aee10c1b3da6d6138b9).
Devo testar mais algumas coisas? Eu imagino que sim, o uso dos parâmetros... O parâmetro `format` não precisa de teste né. Ele já foi testado antes....

2023-09-18 01:20 UTC, FelipeSBarros commented
Aceitei o #30 sabendo que dificultaria aqui. Mas entendo que ainda precisamos fechar esse PR e que a vida é assim, mesmo.
rs

2023-09-18 13:23 UTC, cuducos approved these changes
Boa! Deixei dois comentários de menor importância.
Caso resolve mudar o nome dos parâmetros, não esqueça de atualizar o nome dos testes tb : )

Mas tb podemos fazer essas mudanças menores em PRs menores mais para frente!

2023-09-18 14:13 UTC, FelipeSBarros commented
@cuducos aceitei sua sugestão de usar o nome dos parametros iguais ao da API.
Aproveitei para adicionar um teste mais validando uma chamada com mais de um filtro...

Agora vamos ao que interessa:
antes de fazer o merge, entendo que:
- devo usar o fetch entre a repo que estamos trabalhando e a `master`;
- Identificar os conflitos;
- Ajustá-los e fazer um commit esecífico;
- realizar o merge;

Seria isso?
abraço

2023-09-18 15:26 UTC, cuducos commented
Exato. Eu, pessoalmente, não gosto da interface web do GitHub pois nela não tenho coom rodar os testes antes de commitar.

O que eu faço é, localmente:

1. Ir para `master` com `git checkout master`
2. Atualizar a `master` com `git pull origin master`
3. Voltar para a _feature branch_ com `git checkout add_client_cities`
4. Trazer as alterações da `master` para a `add_client_cities` com `git merge add_client_cities` **e prestar atenção no _output_ desse comando** (ali tem os arquivos com conflito)

Para cada arquivo com conflito:
1. Editar o arquivo solucionando o conflito
2. Adicionar a resolução ao _staging_ com `git add [NOME DO ARQUIVO]`

Depois de tudo feito, `git merge --continue` — se me lembro bem : )

2023-09-18 18:18 UTC, FelipeSBarros commented
@cuducos, quer fazer uma ultima revisão antes do merge?

2023-09-18 19:44 UTC, cuducos requested changes

2023-09-18 19:44 UTC, cuducos commented on Python/crossfire/tests/test_client.py
> +        assert states[0]["name"] == "Rio de Janeiro"
Esse teste está repetido (linhas 123-134)

2023-09-18 19:55 UTC, cuducos requested changes

2023-09-18 19:55 UTC, cuducos commented on Python/crossfire/tests/test_client.py
> +def test_client_load_cities_as_dictionary(client_with_token):
A gente precisa desses dois testes? Eles me parecem testar a mesma coisa.

```suggestion
def test_client_load_cities(client_with_token):
```

2023-09-22 00:50 UTC, cuducos approved these changes
Conversamos fora do GitHub e faz sentido testar com e sem o `format="dict"`…

2023-09-22 00:52 UTC, merged