remove codigo em R e reestrutura repositorio
FelipeSBarros/crossfire pull request #73
Opened 2023-10-28 19:44 UTC by FelipeSBarros

Removi tudo que fosse relacinado ao código R e reestruturei as pastas do repositório, passando `Python/crossfire` para `./crossfire`.
Issue #62

2023-10-28 19:44 UTC, FelipeSBarros commented
Opos. esqueci de rodar testes... calmaê, deixa eu resolver isso, antes de vc revisar.

2023-10-28 19:49 UTC, cuducos requested changes
Independente dos testes:
* Qual a função do arquivo `NAMESPACE`? Podemos excluir esse arquivo, eu acho…
* Aparentemente faltou atualizar o `.gitignore` (ou tem algum motivo que não estou vendo para manter `Python/crossfire` lá?)

2023-10-28 19:50 UTC, FelipeSBarros commented
@cuducos o que eu precisei alterar era o github workflows que ainda estava apontando para a pasta `Python/crossfire`.
Rodando o pytest, estou tendo o seguinte `warning`:
```python
poetry run pytest                                            
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.10.2, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/felipe/repos/crossfire
configfile: pyproject.toml
plugins: black-ng-0.4.1, anyio-4.0.0, ruff-0.1.1, asyncio-0.21.1, isort-3.1.0, env-1.0.1
asyncio: mode=strict
collected 82 items                                                                                                                                                                       

crossfire/__init__.py s.s                                                                                                                                                          [  3%]
crossfire/errors.py s.s                                                                                                                                                            [  7%]
crossfire/logger.py s.s                                                                                                                                                            [ 10%]
crossfire/parser.py s.s                                                                                                                                                            [ 14%]
crossfire/clients/__init__.py s.s                                                                                                                                                  [ 18%]
crossfire/clients/occurrences.py s.s                                                                                                                                               [ 21%]
tests/__init__.py s.s                                                                                                                                                              [ 25%]
tests/conftest.py s.s                                                                                                                                                              [ 29%]
tests/test_client.py s.s......................                                                                                                                                     [ 59%]
tests/test_init.py s.s.......                                                                                                                                                      [ 71%]
tests/test_occurrences_client.py s.s..........                                                                                                                                     [ 87%]
tests/test_parser.py s.s.......                                                                                                                                                    [100%]

==================================================================================== warnings summary ====================================================================================
tests/test_client.py::test_client_load_states
tests/test_client.py::test_client_load_states_as_df
tests/test_client.py::test_client_load_states_raises_format_error
  /home/felipe/repos/crossfire/crossfire/clients/__init__.py:96: DeprecationWarning: There is no current event loop
    loop = get_event_loop()

tests/test_client.py::test_client_load_cities
tests/test_client.py::test_client_load_cities_as_dictionary
tests/test_client.py::test_client_load_cities_with_city_id
tests/test_client.py::testclientes_with_city_name
tests/test_client.py::test_client_load_cities_with_state_id
tests/test_client.py::test_client_load_cities_with_more_than_one_params
  /home/felipe/repos/crossfire/crossfire/clients/__init__.py:106: DeprecationWarning: There is no current event loop
    loop = get_event_loop()

tests/test_client.py::test_client_occurrences
  /home/felipe/repos/crossfire/crossfire/clients/__init__.py:130: DeprecationWarning: There is no current event loop
    loop = get_event_loop()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== 58 passed, 24 skipped, 10 warnings in 2.24s =======================================================================

```

2023-10-28 19:55 UTC, FelipeSBarros commented
> Independente dos testes:
> 
> * Qual a função do arquivo `NAMESPACE`? Podemos excluir esse arquivo, eu acho…
> * Aparentemente faltou atualizar o `.gitignore` (ou tem algum motivo que não estou vendo para manter `Python/crossfire` lá?)

Perfeito. Deixei passar.
Mantive no `.gitignore` a pasta `dist/`. 
Faz sentido?

2023-10-28 19:56 UTC, cuducos requested changes
Parece que faltou revisar o `pyproject.toml` que ainda contém referências à parte em R.

2023-10-28 19:58 UTC, cuducos commented
> Mantive no `.gitignore` a pasta `dist/`

Ok. Qual o papel do `.crossfire` lá? Temos um caso de uso para isso? E o `.idea`?

2023-10-28 20:03 UTC, FelipeSBarros commented
> emos um caso de uso para isso? E o `.idea`?

Eu deixei pois, esse arquivo é criado ao usar IDE Pycharm. Ainda que eu nunca o tenha colocado para versionar, sempre coloco nos `.gitignore` dos projetos.
Acha melhor remover?

2023-10-28 20:12 UTC, cuducos commented
Eu acho que configuração do ambiente de desenvolvimento é uma coisa, e do projeto é outra. O projeto não depende dessa IDE específica, então isso deveria ser tarefa de quem usa essa IDE. Sou adepto de cada um ter um [`.gitignore_global`](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) e não que todo projeto replique defesas contra vestígios de IDEs e ambientes de desenvolvimento dentro do repositório.

2023-10-28 20:23 UTC, cuducos requested changes
O commit 732688f tem uma mensagem que não condiz com o que ele faz. Recomendo um `git commit --amend` para corrigir a mensagem, já que o que o commit faz me parece correto. Depois pode fazer um `git push` utilizando o `--force-with-lease` para sobrescrever a historia do Git nessa branch no GitHub.

2023-10-28 21:09 UTC, FelipeSBarros commented
@cuducos de fato. Estava com o `__pycache__` na cabeça pois estive pesquisando se deveria mantê-lo ou não.
Fiz o sugerido. Não sei se fiz bem. Vejo que o commit [732688f](https://github.com/FelipeSBarros/crossfire/pull/73/commits/732688f3ac234897c24d210d174de3c7eea1dda5) ainda está na histório do repo e um novo commit foi criado: [3736212](https://github.com/FelipeSBarros/crossfire/pull/73/commits/373621243e4200b540834370d15e3faf1d62ff1a).
Era o esperado?

2023-10-29 01:26 UTC, cuducos approved these changes
O _commit_ 732688f [**não** está na _branch_ desse PR](https://github.com/FelipeSBarros/crossfire/pull/73/commits), ótimo : )

2023-10-29 12:14 UTC, merged